cars/urls.py
from django.urls import path

from . import views as car_views


app_name = "cars"

urlpatterns = [
    path("", car_views.car_list, name="car_list"),
    path("<int:pk>/", car_views.car_detail, name="car_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include

app_name = "core"

urlpatterns = [
    # core
    path("", include("core.urls", namespace="core")),
    # shops
    path("shops/", include("shops.urls", namespace="shops")),
    # login
    path("login/", include("login.urls", namespace="login")),
    # accounts
    # path("accounts/", include("allauth.urls")),
    # users
    path("users/", include("users.urls", namespace="users")),
    # search
    path("cars/", include("cars.urls", namespace="cars")),
    # admin
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.urls import path
from shops import views as shop_views
from . import views as core_views

app_name = "core"

urlpatterns = [
    path("", shop_views.home, name="home"),
    path("about_us/", core_views.about_us, name="about_us"),
]

login/urls.py
from django.urls import path
from . import views as login_views

app_name = "login"

urlpatterns = [
    path("", login_views.login_page, name="login_page"),
    path("kakao/", login_views.kakao_login, name="kakao-login"),
    path("kakao/callback/", login_views.kakao_callback, name="kakao-callback"),
    path("naver/", login_views.naver_login, name="naver-login"),
    path("naver/callback/", login_views.naver_callback, name="naver-callback"),
    path("google/", login_views.google_login, name="google-login"),
    path("google/callback/", login_views.google_callback, name="google-callback"),
    path("logout_page/", login_views.logout_page, name="logout_page"),
    path("logout/", login_views.log_out, name="logout"),
]

shops/urls.py
from django.urls import path

from . import views as shop_views


app_name = "shops"

urlpatterns = [
    path("", shop_views.ShopListView.as_view(), name="shop_list"),
    path("<int:id>/", shop_views.shop_detail, name="shop_detail"),
    path("search_main/", shop_views.ShopSearchView.as_view(), name="shop_search_main"),
    path("search_landing/", shop_views.ShopSearchView.as_view(), name="shop_search_landing"),
    path("like/", shop_views.shop_like_ajax, name="shop_like_ajax"),
]

users/urls.py
from django.urls import path
from . import views as user_views


app_name = "users"

urlpatterns = [
    path("mypage/", user_views.render_mypage, name="mypage"),
    path("rating/", user_views.rate_shop_ajax, name="rate_shop_ajax"),
]

templates/partials/footer.html
<!-- universal footer -->

<footer>
    <div class="footer_container">
        <div class="footer_text">
            <h2>보고타</h2>
            <h5>주소: 08826 서울특별시 관악구 관악로 1</h5>
            <h5>이메일: bogotacontacts@gmail.com</h5>
        </div>
    </div>
</footer>

templates/partials/header.html
  <a href="/">Show Me The Car</a>
  
  {% comment %} {% if not user.is_authenticated %} {% endcomment %}
    
  <ul>
    <li><a href="{% url 'login:login_page' %}">Login</a></li>
  </ul>
  {% comment %} {% endif %} {% endcomment %}
    

templates/partials/nav.html
{% load static %}
<!-- navigation bar for landing page -->

<nav>
    <div class="nav__bar__container">
        <div class="logo">
            <a href="{% url 'core:home' %}"><img src="{% static 'images/logo_white.png' %}" alt="logo"></a>

        </div>
        <div class="about">
            <a href="{% url 'core:about_us' %}"><span>서비스 소개</span></a>
            {% if user.is_authenticated %}
            <a href="{% url 'login:logout_page' %}"><span>로그아웃</span></a>
            {% endif %}
        </div>
    </div>
</nav>

templates/partials/nav_search.html
{% load static %}

<!-- navigation bar for search page -->
<nav>
    <div class="nav__bar__container">
        <div class="logo">
            <a href="{% url 'core:home' %}"><img src="{% static 'images/logo_white.png' %}" alt="logo" /></a>
        </div>
        <form action="" class="search__container">

            <div class="search__car">
                {{ form.as_p }}
            </div>
        </form>

        <div class="searchpage">
            <a href="{% url 'shops:shop_search_main' %}"><span>검색 페이지</span></a>
        </div>
        <div class="mypage">
            {% if user.is_authenticated %}
                <a href="{% url 'users:mypage' %}"><span>마이 페이지</span></a>
            {% else %}
                <a href="{% url 'login:login_page' %}"><span>로그인</span></a>
            {% endif %}
        </div>
    </div>
</nav>

templates/partials/ranking.html
{% if best_shops %}
    
<div class="shops__ranking__wrapper">
  <h3>우수 대리점</h3>
  <!--Please insert liked list of shops-->
  <div class="shops__ranking__container">
    <ul>
      {% for shop in best_shops %}
      <li>
        <a href="{% url 'shops:shop_detail' id=shop.id %}"
          >{{ shop.name }} 평점: {{shop.average}}</a
        >
      </li>
      {% endfor %}
    </ul>
    <!--Please insert recent search list of shops-->
  </div>
</div>

{% endif %}