cars/urls.py
from django.urls import path

from . import views as car_views


app_name = "cars"

urlpatterns = [
    path("", car_views.car_list, name="car_list"),
    path("<int:pk>/", car_views.car_detail, name="car_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include

app_name = "core"

urlpatterns = [
    # core
    path("", include("core.urls", namespace="core")),
    # shops
    path("shops/", include("shops.urls", namespace="shops")),
    # login
    path("login/", include("login.urls", namespace="login")),
    # accounts
    # path("accounts/", include("allauth.urls")),
    # users
    path("users/", include("users.urls", namespace="users")),
    # search
    path("cars/", include("cars.urls", namespace="cars")),
    # admin
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

login/urls.py
from django.urls import path
from . import views as login_views

app_name = "login"

urlpatterns = [
    path("", login_views.login_page, name="login_page"),
    path("kakao/", login_views.kakao_login, name="kakao-login"),
    path("kakao/callback/", login_views.kakao_callback, name="kakao-callback"),
    path("naver/", login_views.naver_login, name="naver-login"),
    path("naver/callback/", login_views.naver_callback, name="naver-callback"),
    path("google/", login_views.google_login, name="google-login"),
    path("google/callback/", login_views.google_callback, name="google-callback"),
    path("logout_page/", login_views.logout_page, name="logout_page"),
    path("logout/", login_views.log_out, name="logout"),
]

users/urls.py
from django.urls import path
from . import views as user_views


app_name = "users"

urlpatterns = [
    path("mypage/", user_views.render_mypage, name="mypage"),
    path("rating/", user_views.rate_shop_ajax, name="rate_shop_ajax"),
]

login/models.py
from django.db import models

class Login(models.Model):
    text = models.TextField()

login/views.py
import os
import requests
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from users import models as user_models

DEBUG = bool(os.environ.get("DEBUG"))


def login_page(request):
    return render(request, "login/login.html")


def kakao_login(request):
    if DEBUG:
        redirect_uri = "http://127.0.0.1:8000/login/kakao/callback"
    else:
        redirect_uri = "https://bogota.kr/login/kakao/callback"
    client_id = os.environ.get("KAKAO_ID")
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?response_type=code&client_id={client_id}&redirect_uri={redirect_uri}"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code")
        client_id = os.environ.get("KAKAO_ID")
        if DEBUG:
            redirect_uri = "http://127.0.0.1:8000/login/kakao/callback"
        else:
            redirect_uri = "https://bogota.kr/login/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)
        # print(token_json)
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        profile_json = profile_request.json()
        kakao_account = profile_json.get("kakao_account")
        email = kakao_account.get("email")
        if email is None:
            raise KakaoException()
        properties = profile_json.get("properties")
        nickname = properties.get("nickname")
        thumbnail_image = properties.get("profile_image")
        try:
            user = user_models.User.objects.get(email=email)
            if user.login_method != user_models.User.LOGIN_KAKAO:
                raise KakaoException()
        except user_models.User.DoesNotExist:
            user = user_models.User.objects.create(
                email=email,
                username=email,
                first_name=nickname,
                login_method=user_models.User.LOGIN_KAKAO,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()
        login(request, user)
        return redirect(reverse("core:home"))
    except KakaoException:
        return redirect(reverse("login:login_page"))


def naver_login(request):
    client_id = os.environ.get("NAVER_ID")
    if DEBUG:
        redirect_uri = "http://127.0.0.1:8000/login/naver/callback"
    else:
        redirect_uri = "https://bogota.kr/login/naver/callback"
    state = request.GET.get("csrfmiddlewaretoken")
    return redirect(
        f"https://nid.naver.com/oauth2.0/authorize?client_id={client_id}&response_type=code&redirect_uri={redirect_uri}&state={state}"
    )


class NaverException(Exception):
    pass


def naver_callback(request):
    try:
        code = request.GET.get("code")
        client_id = os.environ.get("NAVER_ID")
        client_secret = os.environ.get("NAVER_SECRET")
        state = request.GET.get("state")
        token_request = requests.get(
            f"https://nid.naver.com/oauth2.0/token?client_id={client_id}&client_secret={client_secret}&grant_type=authorization_code&state={state}&code={code}"
        )
        token_json = token_request.json()
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://openapi.naver.com/v1/nid/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        profile_json = profile_request.json()
        response = profile_json.get("response")
        email = response.get("email")
        if email is None:
            raise NaverException()
        nickname = response.get("name")
        thumbnail_image = response.get("profile_image")
        try:
            user = user_models.User.objects.get(email=email)
            if user.login_method != user_models.User.LOGIN_NAVER:
                raise NaverException()
        except user_models.User.DoesNotExist:
            user = user_models.User.objects.create(
                email=email,
                username=email,
                first_name=nickname,
                login_method=user_models.User.LOGIN_NAVER,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()
        login(request, user)
        return redirect(reverse("core:home"))
    except NaverException:
        return redirect(reverse("login:login_page"))


def google_login(request):
    client_id = os.environ.get("GOOGLE_ID")
    if DEBUG:
        redirect_uri = "http://127.0.0.1:8000/login/google/callback"
    else:
        redirect_uri = "https://bogota.kr/login/google/callback"
    scope = "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
    include_granted_scopes = "true"
    access_type = "offline"
    state = request.GET.get("csrfmiddlewaretoken")
    return redirect(
        f"https://accounts.google.com/o/oauth2/v2/auth?client_id={client_id}&response_type=code&redirect_uri={redirect_uri}&state={state}&scope={scope}&include_granted_scopes={include_granted_scopes}&access_type={access_type}"
    )


class GoogleException(Exception):
    pass


def google_callback(request):
    try:
        code = request.GET.get("code")
        client_id = os.environ.get("GOOGLE_ID")
        client_secret = os.environ.get("GOOGLE_SECRET")
        if DEBUG:
            redirect_uri = "http://127.0.0.1:8000/login/google/callback"
        else:
            redirect_uri = "https://bogota.kr/login/google/callback"
        token_request = requests.post(
            f"https://oauth2.googleapis.com/token?grant_type=authorization_code&code={code}&client_id={client_id}&client_secret={client_secret}&redirect_uri={redirect_uri}"
        )
        token_json = token_request.json()
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://www.googleapis.com/oauth2/v1/userinfo",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        response = profile_request.json()
        email = response.get("email")
        if email is None:
            raise GoogleException()
        nickname = response.get("name")
        thumbnail_image = response.get("picture")
        try:
            user = user_models.User.objects.get(email=email)
            if user.login_method != user_models.User.LOGIN_GOOGLE:
                raise GoogleException()
        except user_models.User.DoesNotExist:
            user = user_models.User.objects.create(
                email=email,
                username=email,
                first_name=nickname,
                login_method=user_models.User.LOGIN_GOOGLE,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()
        login(request, user)
        return redirect(reverse("core:home"))
    except GoogleException:
        return redirect(reverse("login:login_page"))


def logout_page(request):
    return render(request, "login/logout.html")


def log_out(request):
    logout(request)
    return redirect(reverse("core:home"))

templates/login/login.html
{% extends "base.html"%}

{% load static %}
{% comment %} {% load socialaccount %} {% endcomment %}

{% block page_name %}
    로그인{{ block.super }}
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/partials/nav.css' %}">
    <link rel="stylesheet" href="{% static 'styles/login.css' %}">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css">
    {{ block.super }}

    <style>
        .btn-social-login {
          transition: all .2s;
          outline: 0;
          border: 1px solid transparent;
          padding: .5rem !important;
          border-radius: 50%;
          color: #fff;
        }
        .btn-social-login:focus {
          box-shadow: 0 0 0 .2rem rgba(0,123,255,.25);
        }
        .text-dark { color: #343a40!important; }
    </style>

{% endblock %}

{% block nav %}
    {% include "partials/nav.html" %}
{% endblock %}

{% block content %}
<div class="login__container">
    <h1>로그인</h1>
    {% if user.is_authenticated %}
        <h4>{{user.first_name}}님 안녕하세요!</h4>
    {% else %}
        <h4>로그인해서 대리점을 찜해보세요!</h4>
    {% endif %}
    <div class="login__btn__container">
        {% if user.is_authenticated %}
            <button><a href="{% url 'login:logout_page' %}">로그아웃</a></button>
            <button><a href="{% url 'users:mypage' %}">마이페이지</a></button>
        {% else %}
            <form action="{% url 'login:google-login' %}">
                {% csrf_token %}
                <button class='btn-social-login' style='background:#D93025'><i class="xi-2x xi-google"></i></button>
            </form>
            <form action="{% url 'login:naver-login' %}">
                {% csrf_token %}
                <button class='btn-social-login' style='background:#1FC700'><i class="xi-2x xi-naver"></i></button>
            </form>
            <a href="{% url 'login:kakao-login' %}"><button class='btn-social-login' style='background:#FFEB00'><i class="xi-2x xi-kakaotalk text-dark"></i></button></a>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block javascript %}
    <script src="{% static 'js/social_login.js' %}"></script>
{% endblock javascript %}

templates/login/logout.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block page_name %}
    로그아웃{{ block.super }}
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/partials/nav.css' %}">
    <link rel="stylesheet" href="{% static 'styles/logout.css' %}">
{% endblock %}

{% block nav %}
    {% include 'partials/nav.html' %}
{% endblock %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block content %}
    <div class="logout__container">
        <h1>{% trans "로그아웃" %}</h1>
        <p>{% trans "아래 버튼을 눌러 로그아웃을 완료해주세요." %}</p>
        <div class="logout__btn__container">
            <form method="post" action="{% url 'login:logout' %}">
                {% csrf_token %}
                {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                {% endif %}
                <button type="submit">{% trans '로그아웃' %}</button>
            </form>
        </div>
        <h4>{% trans '보고타의 서비스를 이용해 주셔서 감사합니다.' %}</h4>
    </div>
{% endblock %}