cars/urls.py
from django.urls import path

from . import views as car_views


app_name = "cars"

urlpatterns = [
    path("", car_views.car_list, name="car_list"),
    path("<int:pk>/", car_views.car_detail, name="car_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include

app_name = "core"

urlpatterns = [
    # core
    path("", include("core.urls", namespace="core")),
    # shops
    path("shops/", include("shops.urls", namespace="shops")),
    # login
    path("login/", include("login.urls", namespace="login")),
    # accounts
    # path("accounts/", include("allauth.urls")),
    # users
    path("users/", include("users.urls", namespace="users")),
    # search
    path("cars/", include("cars.urls", namespace="cars")),
    # admin
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

login/urls.py
from django.urls import path
from . import views as login_views

app_name = "login"

urlpatterns = [
    path("", login_views.login_page, name="login_page"),
    path("kakao/", login_views.kakao_login, name="kakao-login"),
    path("kakao/callback/", login_views.kakao_callback, name="kakao-callback"),
    path("naver/", login_views.naver_login, name="naver-login"),
    path("naver/callback/", login_views.naver_callback, name="naver-callback"),
    path("google/", login_views.google_login, name="google-login"),
    path("google/callback/", login_views.google_callback, name="google-callback"),
    path("logout_page/", login_views.logout_page, name="logout_page"),
    path("logout/", login_views.log_out, name="logout"),
]

shops/urls.py
from django.urls import path

from . import views as shop_views


app_name = "shops"

urlpatterns = [
    path("", shop_views.ShopListView.as_view(), name="shop_list"),
    path("<int:id>/", shop_views.shop_detail, name="shop_detail"),
    path("search_main/", shop_views.ShopSearchView.as_view(), name="shop_search_main"),
    path("search_landing/", shop_views.ShopSearchView.as_view(), name="shop_search_landing"),
    path("like/", shop_views.shop_like_ajax, name="shop_like_ajax"),
]

users/urls.py
from django.urls import path
from . import views as user_views


app_name = "users"

urlpatterns = [
    path("mypage/", user_views.render_mypage, name="mypage"),
    path("rating/", user_views.rate_shop_ajax, name="rate_shop_ajax"),
]

shops/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from core import models as core_models


class Shop(core_models.TimeStampedModel):
    """ Shop Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField(null=True)
    region = models.CharField(max_length=80, blank=True, null=True)
    city = models.CharField(max_length=80, blank=True, null=True)
    address = models.CharField(max_length=80, blank=True, null=True)
    homepage = models.URLField(max_length=250, blank=True, null=True)
    phone_number = models.CharField(max_length=80, blank=True, null=True)
    average = models.FloatField(blank=True, null=True, default=None)
    like_users = models.ManyToManyField(
        "users.User", related_name="like_shops", blank=True, through="Rating"
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shops:shop_detail", kwargs={"pk": self.pk})

    def get_average_rating(self):
        ratings = self.ratings.all()
        sum_rating = 0
        number_of_ratings = 0
        for rating in ratings:
            if rating.rating is None:
                continue
            sum_rating += int(rating.rating)
            number_of_ratings += 1
        try:
            avg_rating = round((sum_rating / number_of_ratings), 2)
        except ZeroDivisionError:
            avg_rating = 0
        return avg_rating

    get_average_rating.short_description = "Avg. rating"

    def save(self, *args, **kwargs):
        self.average = self.get_average_rating()
        super(Shop, self).save(*args, **kwargs)  # Call the real save() method


class Rating(core_models.TimeStampedModel):

    """ Rating Model Definition """

    user = models.ForeignKey(
        "users.User", related_name="ratings", on_delete=models.CASCADE, null=True
    )
    shop = models.ForeignKey(
        "shops.Shop", related_name="ratings", on_delete=models.CASCADE
    )
    rating = models.IntegerField(
        validators=[MaxValueValidator(5), MinValueValidator(1)],
        blank=True,
        default=None,
        null=True,
    )

    def __str__(self):
        return str(self.rating)

shops/forms.py
from django import forms
from . import models


class SearchForm(forms.Form):

    """ Search Form Definition """

    OPTIONS = [
        ('', '지역'),
        ('서울', '서울특별시'),
        ('부산', '부산광역시'),
        ('대구', '대구광역시'),
        ('인천', '인천광역시'),
        ('광주', '광주광역시'),
        ('대전', '대전광역시'),
        ('울산', '울산광역시'),
        ('세종', '세종특별자치시'),
        ('경기', '경기도'),
        ('강원', '강원도'),
        ('충북', '충청북도'),
        ('충남', '충청남도'),
        ('전북', '전라북도'),
        ('전남', '전라남도'),
        ('경북', '경상북도'),
        ('경남', '경상남도'),
        ('제주', '제주특별자치시도'),
    ]

    city = forms.ChoiceField(initial="Anywhere", required=False, label="", choices=OPTIONS)
    car_model = forms.CharField(label="",
                                widget=forms.TextInput(attrs={'placeholder': '자동차 모델명'}))


# class RatingForm(forms.Form):
#     rating = forms.IntegerField(required=False)

shops/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.urls import reverse
from django.http import Http404, JsonResponse
from . import forms

from shops import models as shops_models
from cars import models as cars_models


def home(request):
    form = forms.SearchForm()
    return render(request, "shops/search_landing.html", {"form": form})


class ShopSearchView(View):

    """ Shop Search View """

    def get(self, request):
        user = request.user
        car_model = request.GET.get("car_model")
        query = car_model
        if car_model:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                print("valid")
                car_model = form.cleaned_data.get("car_model")
                city = form.cleaned_data.get("city")

                filter_args = {}
                if city != "Anywhere":
                    filter_args["city__icontains"] = city

                if car_model is not None:
                    filter_args["car__model_name__icontains"] = car_model

                qs = shops_models.Shop.objects.filter(**filter_args).order_by("created")

                paginator = Paginator(qs, 20, orphans=5)

                page = request.GET.get("/?page", 1)

                shops = paginator.get_page(page)

        else:
            form = forms.SearchForm()
            shops = shops_models.Shop.objects.all().order_by("created")

        context = {
            "user": user,
            "form": form,
            "shops": shops,
            "query": query,
        }

        return render(request, "shops/search_main.html", context=context)


def shop_detail(request, id):
    try:
        shop = get_object_or_404(shops_models.Shop, id=id)
        average = shop.get_average_rating()
        print(average)
        return render(
            request, "shops/shop_detail.html", {"shop": shop, "average": average}
        )
    except shops_models.Shop.DoesNotExist:
        raise Http404()


class ShopListView(ListView):

    """ ShopListView definition """

    model = shops_models.Shop
    paginate_by = 30
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "shops"


@require_POST
def shop_like_ajax(request):
    user = request.user
    pk = request.POST.get("pk")
    action = request.POST.get("action")
    shop = get_object_or_404(shops_models.Shop, pk=pk)
    if action == "add_like":
        shop.like_users.add(user)

    elif action == "remove_like":
        shop.like_users.remove(user)
    shop.save()
    print(shop)
    data = {}
    return JsonResponse(data)

templates/shops/detail.html
{% extends 'base.html' %} {% block page_name %} Detail {% endblock page_name %}
{% block content %} {{ shop.name }}
<br />
<br />
Average Rating: {{ average }}
<br />
<br />
<form method="POST" action="{% url 'shops:give_rating' shop.id %}">
  {% csrf_token %} My Rating:
  <input type="number" name="rating" min="1" max="5" />
  <input type="submit" value="Give Ratings" />
</form>
<span>보유중인 차량:</span>
<ul>
  {% for car in shop.cars.all %}
  <li><a href="{% url 'shops:shop_list'%}?q={{car}}">{{car}}</a></li>
  {% endfor %}
</ul>

{% endblock content %}

templates/shops/give_rating.html
{% extends 'base.html' %}

{% block page_name %}
    detail
{% endblock page_name %}

{% block content %}

{{ shop.name }}
<br />
<br />
Average Rating: {{ average }}
<br />
<br />
<form method="POST" action="{% url 'shops:give_rating' shop.id %}">
    {% csrf_token %}
    My Rating: <input type="number" name="rating" min="1" max="5" />
    <input type="submit" value="Give Ratings">
</form>

{% endblock %}

templates/shops/search_landing.html
{% extends "base.html" %}
{% load static %}

{% block page_name %}간편한 대리점 검색, 보고타!{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/partials/nav.css' %}">
    <link rel="stylesheet" href="{% static 'styles/search_landing.css' %}">
{% endblock %}

{% block nav %}
    {% include "partials/nav.html" %}
{% endblock %}

{% block content %}
    <div class="main__container">
        <!-- 검색 창 -->
        <div class="search__container">
            <h2>모델을 검색해보세요!</h2>
            <form action="{% url 'shops:shop_search_landing'%}" method="get" class="search__container__form">
                <div class="search__car">
                    {{ form.as_p }}
                </div>
                <div class="search__btn__container">
                    {% if user.is_authenticated %}
                        <span><a href="{% url 'users:mypage' %}">마이페이지</a></span>

                    {% else %}
                        <span><a href="{% url 'login:login_page' %}">로그인</a></span>

                    {% endif %}
                        <button>검색</button>

                </div>
            </form>
        </div>
        <div class="slogan__container">
            <h1>"자동차 대리점을 간편하게 찾아보세요"</h1>
            <h3>번거롭기만 했던 자동차 대리점 찾기</h3>
            <h3>이제 보고타가 도와드리겠습니다</h3>
        </div>
    </div>
{% endblock %}

templates/shops/search_main.html
{% extends "base.html" %}

{% load static %}

{% block page_name %}
    대리점 검색{{ block.super }}
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'styles/partials/nav_search.css' %}">
    <link rel="stylesheet" href="{% static 'styles/search_main.css' %}">
    <link rel="stylesheet" href="{% static 'styles/partials/footer.css' %}">
{% endblock %}

{% block nav %}
    {% include "partials/nav_search.html" with form=form %}
{% endblock %}

{% block content %}
    <div class="search__title">
        <h1>검색 결과</h1>
    </div>
    <div class="search__query">
        {% if query %}
            <h3><span>{{ query }}</span><br /><br />모델을 전시 중인 대리점을 클릭해서 조회해보세요!</h3>
        {% else %}
            <h3><span>검색창</span> 에 자동차 모델명을 검색해주세요</h3>
        {% endif %}

    </div>
    <!--main container 시작-->
    <div class="main_content">
        <div class="left_container">
        {% if query %}
            {% for shop in shops %}
                <div>
                    <!-- 좋아요 기능, user가 heart를 눌렀을 때, 대리점의 like_users list에 있으면 list에서 삭제되고 없으면 추가된다 -->

                    {% if user in shop.like_users.all %}
                        <button name="like-button" type="submit" onClick="clickLike(pk={{shop.pk}}, url='{% url 'shops:shop_like_ajax' %}', csrf_token='{{ csrf_token }}')" value="liked" class="" id=like-button{{shop.pk}}>
                        <i class="fas fa-heart"></i>
                        </button>
                    {% else %}
                        <button name="like-button" type="submit" onClick="clickLike(pk={{shop.pk}}, url='{% url 'shops:shop_like_ajax' %}', csrf_token='{{ csrf_token }}')" value="not_liked" class="" id=like-button{{shop.pk}}>
                        <i class="far fa-heart"></i>
                        </button>
                    {% endif %}

                    <div class="left__container__shop__name">
                        <a href="{% url 'shops:shop_detail' shop.id %}">{{ shop.name }}</a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div style="color: #333D4B; font-weight: bold;">
                표시할 차량이 없습니다. 새로운 차량을 검색해주세요.
            </div>
        {% endif %}
        </div>
        <div class="right_container">
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include "partials/footer.html" %}
{% endblock %}

templates/shops/shop_detail.html
{% extends 'base.html' %}
{% load static %}

{% block page_name %}
    대리점 정보{{ block.super }}
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'styles/partials/nav_search.css' %}">
    <link rel="stylesheet" href="{% static 'styles/partials/footer.css' %}">
    <link rel="stylesheet" href="{% static 'styles/shop_detail.css' %}">
    <link rel="stylesheet" href="{% static 'styles/partials/kakao_map_custom_overlay.css' %}">
{% endblock %}

{% block content %}
    <div class="search__detail__title">
        <h1>대리점 조회 결과</h1>
    </div>
    <div class="main__container">
        <div class="shop__detail__container">
            <div class="shop__detail__name">
                <h1>
                    {{ shop.name }}
                    {% if user in shop.like_users.all %}
                        <button name="like-button" type="submit" onClick="clickLike(pk={{shop.pk}}, url='{% url 'shops:shop_like_ajax' %}', csrf_token='{{ csrf_token }}')" value="liked" class="" id=like-button{{shop.pk}}>
                        <i class="fas fa-heart"></i>
                        </button>
                    {% else %}
                        <button name="like-button" type="submit" onClick="clickLike(pk={{shop.pk}}, url='{% url 'shops:shop_like_ajax' %}', csrf_token='{{ csrf_token }}')" value="not_liked" class="" id=like-button{{shop.pk}}>
                        <i class="far fa-heart"></i>
                        </button>
                    {% endif %}
                </h1>
                <h1 id="js-address" style="display: none";>{{ shop.address }}</h1>
            </div>
            <div class="shop__detail__rating">
            {% if not average %}
                <h3 style="color: black;">등록된 별점이 없습니다. 마이페이지에서 별점을 등록해주세요!</h3>
            {% else %}
                {% if 0 <= average and average < 1 %}
                    <h3><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></h3>
                {% elif 1 <= average and average < 2 %}
                    <h3><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></h3>
                {% elif 2 <= average and average < 3 %}
                    <h3><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></h3>
                {% elif 3 <= average and average < 4 %}
                    <h3><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></h3>
                {% elif 4 <= average and average < 5 %}
                    <h3><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i></h3>
                {% elif 5 == average %}
                    <h3><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></h3>
                {% endif %}
            {% endif %}

            </div>
            <div class="shop__detail__list__title">
                <h2>"{{ shop.name }}" 에서 보유중인 모든 차량</h2>
            </div>
            <div class="shop__detail__list__container">
                {% for car in shop.cars.all %}
                    <div class="shop__detail__list__models">
                        <i class="fas fa-angle-double-right"></i><a href="{% url 'shops:shop_search_main'%}?car_model={{car.model_name}}">{{car.model_name}}</a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="map_container">
            <div id="map" style="width:30rem;height:32rem;"></div>
        </div>
    </div>

{% endblock content %}
{% block footer %}
    {% include 'partials/footer.html' %}
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=9bee0ef1392ff520d96df2d43d429725&libraries=services"></script>
    <script>
        var mapContainer = document.getElementById('map'), // 지도를 표시할 div
            mapOption = {
                center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
                level: 3 // 지도의 확대 레벨
            };

        // 지도를 생성합니다
        var map = new kakao.maps.Map(mapContainer, mapOption);

        // 주소-좌표 변환 객체를 생성합니다
        var geocoder = new kakao.maps.services.Geocoder();


        // 주소로 좌표를 검색합니다
        geocoder.addressSearch(document.getElementById('js-address').innerText, function(result, status) {

            // 정상적으로 검색이 완료됐으면
            if (status === kakao.maps.services.Status.OK) {

                var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                // 결과값으로 받은 위치를 마커로 표시합니다
                var marker = new kakao.maps.Marker({
                    map: map,
                    position: coords
                });

                // 커스텀 오버레이에 표시할 컨텐츠 입니다
                // 커스텀 오버레이는 아래와 같이 사용자가 자유롭게 컨텐츠를 구성하고 이벤트를 제어할 수 있기 때문에
                // 별도의 이벤트 메소드를 제공하지 않습니다
                var content = '<div class="wrap">' +
                            '    <div class="info">' +
                            '        <div class="title">' +
                            '            {{ shop.name }}' +
                            '        </div>' +
                            '        <div class="body">' +
                            '            <div class="desc">' +
                            '                <div class="ellipsis">{{ shop.address }}</div>' +
                            '                <div class="jibun ellipsis">{{ shop.phone_number }}</div>' +
                            '            </div>' +
                            '        </div>' +
                            '    </div>' +
                            '</div>';

                // 마커 위에 커스텀오버레이를 표시합니다
                // 마커를 중심으로 커스텀 오버레이를 표시하기위해 CSS를 이용해 위치를 설정했습니다
                var overlay = new kakao.maps.CustomOverlay({
                    content: content,
                    map: map,
                    position: marker.getPosition()
                });

                // 마커를 클릭했을 때 커스텀 오버레이를 표시합니다
                kakao.maps.event.addListener(marker, 'click', function() {
                    overlay.setMap(map);
                });


                // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
                map.setCenter(coords);

            }
        });
    </script>
{% endblock %}