cars/urls.py
from django.urls import path

from . import views as car_views


app_name = "cars"

urlpatterns = [
    path("", car_views.car_list, name="car_list"),
    path("<int:pk>/", car_views.car_detail, name="car_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include

app_name = "core"

urlpatterns = [
    # core
    path("", include("core.urls", namespace="core")),
    # shops
    path("shops/", include("shops.urls", namespace="shops")),
    # login
    path("login/", include("login.urls", namespace="login")),
    # accounts
    # path("accounts/", include("allauth.urls")),
    # users
    path("users/", include("users.urls", namespace="users")),
    # search
    path("cars/", include("cars.urls", namespace="cars")),
    # admin
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

shops/urls.py
from django.urls import path

from . import views as shop_views


app_name = "shops"

urlpatterns = [
    path("", shop_views.ShopListView.as_view(), name="shop_list"),
    path("<int:id>/", shop_views.shop_detail, name="shop_detail"),
    path("search_main/", shop_views.ShopSearchView.as_view(), name="shop_search_main"),
    path("search_landing/", shop_views.ShopSearchView.as_view(), name="shop_search_landing"),
    path("like/", shop_views.shop_like_ajax, name="shop_like_ajax"),
]

users/urls.py
from django.urls import path
from . import views as user_views


app_name = "users"

urlpatterns = [
    path("mypage/", user_views.render_mypage, name="mypage"),
    path("rating/", user_views.rate_shop_ajax, name="rate_shop_ajax"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from core import managers as core_managers


class User(AbstractUser):

    """ Custom User Model """

    LOGIN_NAVER = "naver"
    LOGIN_GOOGLE = "google"
    LOGIN_KAKAO = "kakao"

    LOGIN_CHOICES = (
        (LOGIN_NAVER, "Naver"),
        (LOGIN_GOOGLE, "Google"),
        (LOGIN_KAKAO, "Kakao"),
    )

    avatar = models.ImageField(blank=True)
    birthdate = models.DateField(blank=True, null=True)
    superhost = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    login_method = models.CharField(
        max_length=50, choices=LOGIN_CHOICES, default=LOGIN_KAKAO
    )
    objects = core_managers.CustomUserManager()

users/forms.py
from django import forms
from shops.models import Rating
from .widgets import RateShopWidget


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["rating"]
        widgets = {
            "rating": RateShopWidget,
        }
        labels = {
            "rating": "",
        }

users/views.py
from django.core import serializers
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_protect

from .forms import RatingForm
from . import models as user_models
from shops import models as shop_models


def render_mypage(request):
    user = request.user
    like_shops = user.like_shops.all()
    best_shops = shop_models.Shop.objects.exclude(average=None).order_by("-average")[
        :10
    ]
    # rating = user.ratings.all().filter(shop=like_shops)
    # print(like_shops)
    rating_form = RatingForm()
    # print(rating_form)

    ctx = {
        "user": user,
        "like_shops": like_shops,
        "best_shops": best_shops,
        "rating_form": rating_form,
    }

    return render(request, "users/mypage.html", ctx)


@require_POST
def rate_shop_ajax(request):
    print(request.POST)
    user = request.user
    shop = shop_models.Shop.objects.get(id=request.POST.get("shop_id"))
    print(user)
    print(shop)
    my_rating = request.POST.get("my_rating")
    rating = shop_models.Rating.objects.get(user=user, shop=shop)
    rating.rating = my_rating
    rating.save()
    shop.save()
    print(rating)
    qs = shop_models.Shop.objects.exclude(average=None).order_by("-average")[:10]
    best_shops = serializers.serialize("json", qs)
    return JsonResponse(best_shops, safe=False)

templates/users/mypage.html
{% extends "base.html" %}

{% load static %}
{% load get_shop_rating %}

{% block page_name %}
    마이 페이지{{ block.super }}
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'styles/partials/nav_search.css' %}">
    <link rel="stylesheet" href="{% static 'styles/mypage.css' %}">
    <link rel="stylesheet" href="{% static 'styles/partials/footer.css' %}">
{% endblock %}

    <!--nav bar identical to search.html-->
{% block nav %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <!--my page title-->
    <div class="mypage__title">
        <h1>마이 페이지</h1>
    </div>

    <!--Liked shops list-->
    <div class="main__container">
        <div class="left__container">
        <div class="link__ranking__container">
            <div class="brand__link__wrapper">
                <h3>시승 신청 바로가기</h3>
                <div class="brand__link__container">
                    <!-- <li><a href="https://www.genesis.com/kr/ko/genesis-test-drive.html" target="_blank">제네시스</a></li> -->
                    <div><a href="https://www.hyundai.com/kr/ko/e/vehicles/test-driving" target="_blank">현대 자동차</a></div>
                    <div><a href="https://www.kia.com/kr/experience-center/test-service/default.html" target="_blank">기아 자동차</a></div>
                    <div><a href="https://www.chevrolet.co.kr/purchase/test-drive.gm" target="_blank">쉐보레</a></div>
                    <div><a href="http://www.smotor.com/kr/purchase/td_center/newcar/index.html" target="_blank">쌍용 자동차</a></div>
                    <div><a href="https://www.renaultsamsungm.com/new/side/app_testdrive.jsp" target="_blank">르노 삼성</a></div>
                </div>
            </div>
            <div class="shops__ranking__wrapper">
                <h3>우수 대리점</h3>
                <div class="shops__ranking__container">
                    {% for shop in best_shops %}
                        <div>
                            <h4><a href="{% url 'shops:shop_detail' id=shop.id %}">{{ shop.name }}</a></h4>
                            {% if 0 <= shop.average and shop.average < 1 %}
                                <h3><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></h3>
                            {% elif 1 <= shop.average and shop.average < 2 %}
                                <h3><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></h3>
                            {% elif 2 <= shop.average and shop.average < 3 %}
                                <h3><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></h3>
                            {% elif 3 <= shop.average and shop.average < 4 %}
                                <h3><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></h3>
                            {% elif 4 <= shop.average and shop.average < 5 %}
                                <h3><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i></h3>
                            {% elif 5 == shop.average %}
                                <h3><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></h3>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
            <!--ad banner-->
            <div class="ad__banner">
            </div>
        </div>
        <div class="right__container__wrapper">
            <h3>{{ user.first_name }}님이 찜한 대리점</h3>
            <div class="right__container">
                {% for like_shop in like_shops %}
                    <div class="right__shop__container">
                        <div class="right__container__shop__name">
                            <a href="{% url 'shops:shop_detail' id=like_shop.id %}">{{ like_shop.name }}</a>
                        </div>
                        <div class="rating__container">
                            <form class="rating__form " id="jsForm{{like_shop.id}}" action="" onsubmit="clickRate(shop_id={{like_shop.id}}, url='{% url 'users:rate_shop_ajax' %}', event)" style="display: none;">
                                {% csrf_token %}
                                <input type="hidden" name="shop_id" value="{{ like_shop.id }}"/>
                                {{ rating_form.as_table }} <br />
                                <button class="jsRateBtn rate_button" type="submit">별점 주기</button>
                            </form>
                            <div>내가 준 별점: 
                                <i class="fas fa-star" style="color: gold;"></i>
                                {% comment %} <svg class="svg-inline--fa fa-star fa-w-18" aria-hidden="true" data-prefix="fas" data-icon="star" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg="">
                                    <path fill="currentColor" d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"></path>
                                </svg> {% endcomment %}
                                <span id="jsMyRating{{like_shop.id}}">{{like_shop.ratings.all|get_shop_rating:user}}</span>
                            </div>
                            <button class="edit_button" onclick="clickEditRating(shop_id={{like_shop.id}}, event)" id="jsEditRating{{like_shop.id}}">수정하기</button>
                            <button class="cancel_button" onclick="clickCancelEditRating(shop_id={{like_shop.id}}, event)" id="jsCancelEditRating{{like_shop.id}}" style="display: none;">취소</button>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}
{% block footer %}
    {% include "partials/footer.html" %}
{% endblock %}
{% block javascript %}
{% endblock javascript %}